#!/bin/bash

# Make sure we're on a Mac
if [[ "$OSTYPE" =~ ^darwin ]]; then
    echo "Since this is a Mac, let's roll Homebrew."
else
    echo "This ain't a Mac! Exiting now."
    exit 0
fi

# Update Homebrew formulae & upgrade existing packages
echo "Updating Homebrew and upgrading existing packages"
brew update && brew upgrade

# Grab duplicate formulae
brew tap homebrew/dupes

# Array list of Homebrew formulae to install
myBrew=( mercurial git bash ctags lynx wget zsh coreutils vim svn python fishfish wine valgrind tig cowsay fortune ssh-copy-id mutt msmtp offline-imap notmuch contacts tree)

# Array list of dupes to install
myDupes=( )

# Run installs
for i in ${myBrew[*]}
do
    brew install $i
done

for i in ${myDupes[*]}
do
    brew install $i
done

# Clean up the Cellar
brew cleanup
