#!/bin/bash

# Make sure we're on a Mac
if [[ "$OSTYPE" =~ ^darwin ]]; then
    echo "Since this is a Mac, let's roll Homebrew."
else
    echo "This ain't a Mac! Exiting now."
    exit 0
fi

# Update Homebrew formulae & upgrade existing packages
echo "Updating Homebrew and upgrading existing packages"
brew update && brew upgrade

# Grab duplicate formulae
brew tap homebrew/dupes
brew tap homebrew/php
brew tap caskroom/cask

# Array list of Homebrew formulae to install
myBrew=( bash bash-completion zsh wget colordiff "vim --override-system-vi" grep ssh-copy-id coreutils cowsay ctags fortune git openssh "php56 --with-gmp --with-phpdbg" php56-xdebug php56-mcrypt python python3 tree node tig homebrew/php/composer brew-cask wp-cli zsh-completion zsh-syntax-highlighting)

# Array list of dupes to install
myDupes=( )

# Run installs
for i in ${myBrew[*]}
do
    brew install $i
done

for i in ${myDupes[*]}
do
    brew install $i
done

# Clean up the Cellar
brew cleanup
